ProyectoTesisAI/SNAI_Cliente

src/main/java/epn/edu/ec/servicios/ActividadesInstrumentosServicio.java
src/main/java/epn/edu/ec/servicios/AdolescenteInfractorCAIServicio.java
src/main/java/epn/edu/ec/servicios/AdolescenteInfractorServicio.java
src/main/java/epn/edu/ec/servicios/AdolescenteInfractorUDIServicio.java
src/main/java/epn/edu/ec/servicios/AsistenciaAdolescentesServicio.java
src/main/java/epn/edu/ec/servicios/CaiServicio.java
src/main/java/epn/edu/ec/servicios/ConexionServicio.java
src/main/java/epn/edu/ec/servicios/CumplimientoMedidaCAIServicio.java
src/main/java/epn/edu/ec/servicios/DatosProvinciaCantonServicio.java
src/main/java/epn/edu/ec/servicios/DatosTipoPenalCAIServicio.java
src/main/java/epn/edu/ec/servicios/DetalleInfraccionCAIServicio.java
src/main/java/epn/edu/ec/servicios/EjeEducativoServicio.java
src/main/java/epn/edu/ec/servicios/EjeLaboralServicio.java
src/main/java/epn/edu/ec/servicios/EjeSaludServicio.java
src/main/java/epn/edu/ec/servicios/EjecucionMedidaServicio.java
src/main/java/epn/edu/ec/servicios/EstadoCumplimientoMedidaServicio.java

Implementacion de autenticacion en los metodos del servidor

JAVIER: Cambios del 23/07/2019 08:50

---

src/main/java/epn/edu/ec/controlador/PanelReporteControlador.java
src/main/java/epn/edu/ec/modelo/Reporte1.java
src/main/java/epn/edu/ec/modelo/Reporte2.java
src/main/java/epn/edu/ec/modelo/Reporte3.java
src/main/java/epn/edu/ec/modelo/Reporte4.java
src/main/java/epn/edu/ec/modelo/Reporte5.java
src/main/java/epn/edu/ec/modelo/Reporte6N.java
src/main/java/epn/edu/ec/modelo/Reporte6S.java
src/main/java/epn/edu/ec/modelo/Reporte7.java
src/main/java/epn/edu/ec/servicios/AdolescenteInfractorServicio.java
src/main/webapp/paginas/admin/reporte/reporteEdadCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteEdadFechaFuturaCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteEdadFechaFuturaUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteEdadNivelEducativoCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteEdadNivelEducativoUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteEdadUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteFechaIngresoCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteLugarResidenciaCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteLugarResidenciaUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteMedidasCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteMedidasUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteNacionalidadCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteNacionalidadUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteNivelEducativoCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteNivelEducativoUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteTipoDelitoCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteTipoDelitoUDI.xhtml

JAVIER: Cambios del 30/07/2019 15:30

---

src/main/java/epn/edu/ec/controlador/PanelReporteControlador.java
src/main/java/epn/edu/ec/modelo/Reporte6N.java
src/main/java/epn/edu/ec/modelo/Reporte6S.java
src/main/java/epn/edu/ec/modelo/Reporte7.java
src/main/java/epn/edu/ec/servicios/AdolescenteInfractorServicio.java
src/main/webapp/paginas/admin/reporte/reporteEdadCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteEdadFechaFuturaCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteEdadFechaFuturaUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteEdadNivelEducativoCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteEdadNivelEducativoUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteEdadUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteFechaIngresoCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteLugarResidenciaCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteLugarResidenciaUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteMedidasCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteMedidasUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteNacionalidadCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteNacionalidadUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteNivelEducativoCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteNivelEducativoUDI.xhtml
src/main/webapp/paginas/admin/reporte/reporteTipoDelitoCAI.xhtml
src/main/webapp/paginas/admin/reporte/reporteTipoDelitoUDI.xhtml

JAVIER: Cambios del 31/07/2019 11:05

---

src/main/java/epn/edu/ec/controlador/UsuarioControlador.java
src/main/java/epn/edu/ec/modelo/Usuario.java
src/main/java/epn/edu/ec/servicios/RolCentroUsuarioServicio.java
src/main/java/epn/edu/ec/servicios/UsuarioServicio.java
src/main/java/epn/edu/ec/utilidades/Constantes.java
src/main/java/epn/edu/ec/utilidades/EnlacesPrograma.java
src/main/webapp/paginas/admin/admin_usuario.xhtml
src/main/webapp/plantillas/admin/administracion_asignar_rol_centro.xhtml
src/main/webapp/plantillas/admin/administracion_crear_usuario.xhtml

JAVIER: Cambios del 01/08/2019 11:20

---

src/main/java/epn/edu/ec/controlador/UsuarioControlador.java
src/main/java/epn/edu/ec/servicios/UsuarioServicio.java
src/main/java/epn/edu/ec/utilidades/EnlacesPrograma.java
src/main/webapp/paginas/admin/panel_administracion_usuario.xhtml
src/main/webapp/plantillas/admin/administracion_activar_usuario.xhtml
src/main/webapp/plantillas/admin/administracion_desactivar_usuario.xhtml

JAVIER: Cambios del 01/08/2019 22:30

---

src/main/java/epn/edu/ec/controlador/TallerControlador.java
src/main/java/epn/edu/ec/servicios/LoginServicio.java
src/main/webapp/plantillas/user/taller/plantilla_taller.xhtml

JAVIER: Cambios del 02/08/2019 11:00

---

src/main/java/epn/edu/ec/controlador/DetalleInfraccionControlador.java
src/main/java/epn/edu/ec/controlador/InformacionCambioMedidaControlador.java
src/main/java/epn/edu/ec/controlador/RepresentanteCAIControlador.java
src/main/java/epn/edu/ec/utilidades/Validaciones.java
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_eje_salud.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_info_cambio_medida.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_info_geografica.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_lista_ejecucion_medida.xhtml

Update para Adolescente Infractor de CAI y sus diversas clases.
Arreglo de Validaciones

JAVIER: Cambios del 05/08/2019 17:00

---

src/main/java/epn/edu/ec/controlador/EjeEducativoCAIControlador.java
src/main/java/epn/edu/ec/controlador/EjeSaludCAIControlador.java
src/main/java/epn/edu/ec/controlador/InformacionCambioMedidaControlador.java
src/main/java/epn/edu/ec/controlador/MotivoEgresoCAIControlador.java
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_adolescente_cai.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_motivo_egreso.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_representante.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_adolescente_cai.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_eje_salud.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_lista_ejecucion_medida.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_motivo_egreso.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_representante.xhtml

Update para Adolescente Infractor de CAI y sus diversas clases.
Arreglo de validaciones para crear y editar

JAVIER: Cambios del 07/08/2019 17:00

---

src/main/java/epn/edu/ec/controlador/AdolescenteInfractorCAIControlador.java
src/main/java/epn/edu/ec/controlador/AdolescenteInfractorUDIControlador.java
src/main/java/epn/edu/ec/controlador/InformacionJudicialControlador.java
src/main/java/epn/edu/ec/controlador/MedidaSocioEducativaControlador.java
src/main/java/epn/edu/ec/servicios/AdolescenteInfractorCAIServicio.java
src/main/webapp/paginas/CAI2/user/crear/psicologo/panel_crear_cai.xhtml
src/main/webapp/paginas/user/uzdi/udi.xhtml
src/main/webapp/plantillas/admin/uzdi/crear/plantilla_adolescente_uzdi.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_adolescente_cai.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_adolescente_cai.xhtml

Update para Adolescente Infractor de CAI e Adolescente Infractor de UDI

JAVIER: Cambios del 07/08/2019 14:05

---

src/main/java/epn/edu/ec/controlador/AdministracionMenuControlador.java
src/main/java/epn/edu/ec/utilidades/EnlacesPrograma.java
src/main/webapp/plantillas/admin/administracion_activar_usuario.xhtml
src/main/webapp/plantillas/admin/administracion_desactivar_usuario.xhtml
src/main/webapp/plantillas/admin/reporte/reporteTipoDelitoCAI.xhtml
src/main/webapp/plantillas/admin/reporte/reporteTipoDelitoUDI.xhtml
src/main/webapp/plantillas/admin/uzdi/crear/plantilla_info_infraccion.xhtml
src/main/webapp/plantillas/admin/uzdi/editar/plantilla_info_infraccion.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_lista_detalle_infraccion.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_lista_detalle_infraccion.xhtml
src/main/webapp/templates/menu.xhtml

Update para la administracion de los usuarios, cambio de comobox de primefaces a boostfaces, creacion de URL para el menu de administracion de usuarios

JAVIER: Cambios del 08/08/2019 08:25

---

src/main/java/epn/edu/ec/controlador/PanelAdolescenteInfractorUDIControlador.java
src/main/java/epn/edu/ec/controlador/PanelReporteControlador.java
src/main/java/epn/edu/ec/servicios/AdolescenteInfractorServicio.java
src/main/java/epn/edu/ec/servicios/AdolescenteInfractorUDIServicio.java
src/main/webapp/plantillas/admin/reporte/reporteEdadFechaFuturaCAI.xhtml
src/main/webapp/plantillas/admin/reporte/reporteEdadFechaFuturaUDI.xhtml
src/main/webapp/plantillas/admin/reporte/reporteTipoDelitoCAI.xhtml
src/main/webapp/plantillas/admin/reporte/reporteTipoDelitoUDI.xhtml

Update para reportes, servicio de elminar adolescente infractor

JAVIER: Cambios del 08/08/2019 11:45

---

src/main/java/epn/edu/ec/controlador/PanelAdolescenteInfractorCAIControlador.java
src/main/java/epn/edu/ec/controlador/PanelInformeControlador.java
src/main/java/epn/edu/ec/controlador/PanelTallerControlador.java
src/main/java/epn/edu/ec/servicios/InformeServicio.java
src/main/java/epn/edu/ec/servicios/TallerServicio.java
src/main/webapp/paginas/CAI2/admin/cai.xhtml
src/main/webapp/paginas/admin/informe/panel_informe.xhtml
src/main/webapp/paginas/admin/taller/panel_taller.xhtml
src/main/webapp/paginas/admin/uzdi/udi.xhtml

Update para servicio de elminar adolescente infractor y sus diferentes clases
Update en eliminar para solo permitir que borre el adolescente infractor, el taller e informe, solo por parte del ADMINISTRADOR

JAVIER: Cambios del 08/08/2019 11:15

---

src/main/java/epn/edu/ec/controlador/PanelAdolescenteInfractorCAIControlador.java
src/main/java/epn/edu/ec/controlador/PanelAdolescenteInfractorUDIControlador.java
src/main/java/epn/edu/ec/controlador/PanelInformeControlador.java
src/main/java/epn/edu/ec/controlador/PanelTallerControlador.java
src/main/java/epn/edu/ec/servicios/AdolescenteInfractorServicio.java
src/main/java/epn/edu/ec/servicios/InformeServicio.java
src/main/java/epn/edu/ec/servicios/TallerServicio.java
src/main/webapp/paginas/CAI2/admin/cai.xhtml
src/main/webapp/paginas/admin/informe/panel_informe.xhtml
src/main/webapp/paginas/admin/panel_administracion_usuario.xhtml
src/main/webapp/paginas/admin/taller/panel_taller.xhtml
src/main/webapp/paginas/admin/taller/taller_editar.xhtml
src/main/webapp/paginas/admin/uzdi/udi.xhtml
src/main/webapp/plantillas/admin/informe/plantilla_informe_editar.xhtml
src/main/webapp/plantillas/admin/taller/plantilla_taller_editar.xhtml

Update para servicio de elminar adolescente infractor y sus diferentes clases
Update en eliminar para solo permitir que borre el adolescente infractor, el taller e informe, solo por parte del ADMINISTRADOR

JAVIER: Cambios del 08/08/2019 12:35

---

src/main/java/epn/edu/ec/controlador/AdolescenteInfractorCAIControlador.java
src/main/java/epn/edu/ec/controlador/AdolescenteInfractorUDIControlador.java
src/main/java/epn/edu/ec/controlador/IdentificacionGeograficaCAIControlador.java
src/main/java/epn/edu/ec/controlador/IdentificacionGeograficaUDIControlador.java
src/main/java/epn/edu/ec/controlador/MedidaSocioEducativaControlador.java
src/main/java/epn/edu/ec/modelo/DatosPais.java
src/main/java/epn/edu/ec/modelo/MedidaSocioeducativa.java
src/main/java/epn/edu/ec/servicios/DatosPaisServicio.java
src/main/java/epn/edu/ec/utilidades/Constantes.java
src/main/webapp/paginas/cai/adolescentes_cai/ai_cai_crear.xhtml
src/main/webapp/paginas/udi/adolescentes_udi/ai_udi_crear.xhtml
src/main/webapp/plantillas/admin/uzdi/crear/plantilla_eje_salud.xhtml
src/main/webapp/plantillas/admin/uzdi/crear/plantilla_info_geografica.xhtml
src/main/webapp/plantillas/admin/uzdi/crear/plantilla_med_socioeducativa.xhtml
src/main/webapp/plantillas/admin/uzdi/editar/plantilla_info_geografica.xhtml
src/main/webapp/plantillas/admin/uzdi/editar/plantilla_med_socioeducativa.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_eje_educativo.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_eje_salud.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_info_geografica.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_lista_detalle_infraccion.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_lista_ejecucion_medida.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_eje_educativo.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_eje_salud.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_info_geografica.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_lista_detalle_infraccion.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_lista_ejecucion_medida.xhtml

Cambios menores en las interfaces y sus controladores,
creacion de un entidad DatosPais

JAVIER: Cambios del 18/08/2019 9:00

---

src/main/java/epn/edu/ec/controlador/TallerControlador.java
src/main/java/epn/edu/ec/controlador/TallerEditarControlador.java
src/main/java/epn/edu/ec/servicios/ItemTallerServicio.java
src/main/webapp/plantillas/admin/taller/plantilla_taller_editar.xhtml
src/main/webapp/plantillas/user/taller/plantilla_taller.xhtml

-EDICION DE ITEMS TALLER EN EDITAR Y CREAR TALLER

JAVIER: Cambios del 29/08/2019 10:22

---

src/main/webapp/plantillas/admin/taller/plantilla_taller_editar.xhtml
src/main/webapp/plantillas/user/taller/plantilla_taller.xhtml

Cambios menores con añadir iconos

JAVIER: Cambios del 29/08/2019 10:53

---

src/main/java/epn/edu/ec/controlador/UsuarioControlador.java
src/main/java/epn/edu/ec/utilidades/PasswordGenerator.java
src/main/webapp/plantillas/admin/administracion_crear_usuario.xhtml

Cambios menores con añadir iconos

JAVIER: Cambios del 29/08/2019 16:28

---

src/main/java/epn/edu/ec/controlador/EjecucionMedidaControlador.java
src/main/java/epn/edu/ec/controlador/IdentificacionGeograficaCAIControlador.java
src/main/java/epn/edu/ec/controlador/IdentificacionGeograficaUDIControlador.java
src/main/java/epn/edu/ec/controlador/InformacionInfraccionControlador.java
src/main/java/epn/edu/ec/controlador/MedidaSocioEducativaControlador.java
src/main/webapp/plantillas/admin/uzdi/crear/plantilla_med_socioeducativa.xhtml
src/main/webapp/plantillas/admin/uzdi/editar/plantilla_med_socioeducativa.xhtml

Cambios en medidas para una actualizacion automatica, y gestion de sout

JAVIER: Cambios del 29/08/2019 17:50

---

src/main/java/epn/edu/ec/controlador/AdministracionMenuControlador.java
src/main/java/epn/edu/ec/controlador/DetalleInfraccionControlador.java
src/main/java/epn/edu/ec/utilidades/Validaciones.java
src/main/webapp/paginas/cai/admin/editar/panel_crear_cai.xhtml
src/main/webapp/paginas/cai/user/crear/inspectorEducador/panel_crear_cai.xhtml
src/main/webapp/plantillas/admin/uzdi/crear/plantilla_med_socioeducativa.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_lista_detalle_infraccion.xhtml
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_lista_ejecucion_medida.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_eje_salud.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_lista_detalle_infraccion.xhtml
src/main/webapp/plantillas/cai/editar/plantilla_lista_ejecucion_medida.xhtml
src/main/webapp/plantillas/cai/ver/plantilla_detalle_infraccion.xhtml
src/main/webapp/plantillas/cai/ver/plantilla_ejecucion_medida.xhtml
src/main/webapp/templates/menu.xhtml

-Validaciones del para judicial
-cambio de validacion de edad
-Asignacion de reporte a otros roles

JAVIER: Cambios del dia del programador:

---

src/main/java/epn/edu/ec/controlador/DetalleInfraccionControlador.java
src/main/webapp/plantillas/cai/crear_admin_user/plantilla_lista_detalle_infraccion.xhtml

-Validaciones del para judicial

JAVIER: Cambios del 16/09/2019

---

src/main/java/epn/edu/ec/controlador/InformacionJudicialControlador.java
src/main/java/epn/edu/ec/controlador/MedidaSocioEducativaControlador.java
src/main/java/epn/edu/ec/controlador/PanelAdolescenteInfractorUDIControlador.java
src/main/java/epn/edu/ec/controlador/ValidarAccesoControlador.java
src/main/webapp/paginas/uzdi/admin/panel_crear_udi.xhtml
src/main/webapp/paginas/uzdi/admin/panel_editar_udi.xhtml
src/main/webapp/paginas/uzdi/user/juridico/panel_crear_udi.xhtml
src/main/webapp/paginas/uzdi/user/liderUzdi/panel_crear_udi.xhtml

-Redireccion en UZDI, eje judicial y medidas socioeducativas

JAVIER: Cambios del 16/09/2019 11:15

---

src/main/webapp/paginas/cai/user/cai.xhtml
src/main/webapp/paginas/uzdi/user/udi.xhtml

-Arreglo de interfaz de panl cai y uzdi de user

JAVIER: Cambios del 16/09/2019 11:25

---

src/main/webapp/plantillas/user/informe/plantilla_informe.xhtml
src/main/webapp/plantillas/user/informe/plantilla_informe_ver.xhtml
src/main/webapp/plantillas/user/taller/plantilla_taller.xhtml
src/main/webapp/plantillas/user/taller/plantilla_taller_ver.xhtml

-Arreglo de interfaz de panel taller e informe

JAVIER: Cambios del 16/09/2019 11:33

---

src/main/java/epn/edu/ec/controlador/EjecucionMedidaControlador.java
src/main/java/epn/edu/ec/controlador/InformacionJudicialControlador.java
src/main/java/epn/edu/ec/controlador/LoginController.java
src/main/java/epn/edu/ec/controlador/MedidaSocioEducativaControlador.java
src/main/webapp/paginas/uzdi/user/juridico/panel_crear_udi.xhtml
src/main/webapp/paginas/uzdi/user/psicologo/panel_crear_udi.xhtml
src/main/webapp/paginas/uzdi/user/trabajadorSocial/panel_crear_udi.xhtml
src/main/webapp/plantillas/admin/reporte/reporteMedidasCAI.xhtml

-Arreglo de interfaz de panel taller e informe

JAVIER: Cambios del 16/09/2019 14:41

---

src/main/java/epn/edu/ec/controlador/AdministracionMenuControlador.java
src/main/java/epn/edu/ec/controlador/AdolescenteInfractorCAIEditarControlador.java
src/main/java/epn/edu/ec/controlador/AdolescenteInfractorUDIEditarControlador.java
src/main/java/epn/edu/ec/servicios/AdolescenteInfractorCAIServicio.java
src/main/java/epn/edu/ec/servicios/AdolescenteInfractorUDIServicio.java

-Cambios en EditarAdolescenteCAI y EditarAdolescenteUZDI
-Crear Registro para SubDirector habilitado

JAVIER: Cambios del 30/10/2019 16:00
